language: python

python:
    - 3.7
    - 3.8
    - 3.9

env:
  - DJANGO_VERSION=2.2.24
  - DJANGO_VERSION=3.1.12
  - DJANGO_VERSION=3.2.4

install:
    - pip install -r requirements.txt
    - pip install mixer
    - pip install python-coveralls
    - pip install coverage==4.5.4

script:
    - coverage run --source=candlestick ./test.sh

after_success:
  - coveralls
