# Generated by Django 3.2.4 on 2021-06-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('exchange', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
