# Generated by Django 3.2.4 on 2021-06-18 16:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candlestick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('resolution', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^\\d{0,2}[smHDWMY]$')])),
                ('open', models.DecimalField(decimal_places=5, max_digits=9)),
                ('low', models.DecimalField(decimal_places=5, max_digits=9)),
                ('high', models.DecimalField(decimal_places=5, max_digits=9)),
                ('close', models.DecimalField(decimal_places=5, max_digits=9)),
                ('volume', models.IntegerField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='candlestick.instrument')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
