# Generated by Django 3.2.4 on 2021-06-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlestick', '0002_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
